# Site Settings
baseurl: ""
url : "https://arabae.github.io"

# Blog Settings
theme_settings :
  title : ARa Blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : ARa Bae
    description: "Speaker Recognition Blog"

    experience :
      - start : 2018-01
        end : 2018-08
        experience : 기동어 발화 데이터를 이용한 화자 인식 기술 개발
    skills : 
      - skill : MATLAB
        value : 70
      - skill : C/C++
        value : 30
      
    experience :
      - start : 2019-02
        end : 2019-09
        experience : 사용자 정의 기동어 인식 기술 개발
    skills : 
      - skill : python
        value : 10
      - skill : MATLAB
        value : 20
      - skill : C/C++
        value : 70

    experience :
      - start : 2020-01
        end : 2020-07
        experience : 전화 녹취 음성에서 화자분리 및 음원분리 기술 구현 용역 개발
    skills :
      - skill : MATLAB
        value : 10    
      - skill : python
        value : 90
        
  # Icons
  icons :
    email: arbae@inu.ac.kr
    linkedin:  # Full URL 
    github: arabae
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : arabae.github.io

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
