name: ARa's DevBlog
author: ARa Bae
url: https://arabae.github.io/
baseurl:
resume_site: https://github.com/arabae
description: Speech/Speaker Recognition Study
github_username: arabae
github: https://github.com/arabae
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor/bundle/', 'vendor/cache/', 'vendor/gems/', 'vendor/ruby/']
highlighter: rouge
markdown: kramdown
lsi: false
excerpt_separator: "\n\n"
incremental: false
comments :
  gitalk :
    clientID : 5304ae17c5ba0ce3b2aa
    clientSecret : 22801b52c86101ff074072faa1631475954d2936
    repo : arabae.github.io
    owner : arabae
    admin : arabae
analytics:
  provider: "google-gtag"
  google:
    tracking_id : "UA-180957529-1"
    measurement_id : "G-WFYXX17J4G"
    anonymize_ip : # true, false (default)
