# Site Settings
baseurl: ""
url : "https://arabae.github.io"

# Blog Settings
theme_settings :
  title : ARa Blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : ARa Bae
    description: "Speaker Recognition Blog"
    experience :
      - start : 2016-12
        end : 2021-02
        experience : IMPRESS 연구원
    skills : 
      - skill : Python
        value : 90
      - skill : MATLAB
        value : 75
      - skill : C++
        value : 60
        
  # Icons
  icons :
    email: arbae@inu.ac.kr
    linkedin:  # Full URL 
    github: arabae
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : arabae.github.io

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
